[package]
name = "memgrep"
version = "0.1.0"
authors = ["Erkki Seppälä <flux@inside.org>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3.9"
lazy_static = "1.4.0"
regex = "1.3.9"
memmap = "0.7.0"
clap = "3.0.0-beta.2"
