on: [push]

name: CI

jobs:
  build_and_test:
    name: Memgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libhyperscan-dev
        run: sudo apt-get install libhyperscan-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo +nightly build --release --all-features
